### ISSUE TITLE
Setting maximum-scale in viewport meta has long been considered bad.

### ISSUE THREAD

**Issue by tomliv** [ericalli/static-site-boilerplate#13]
**Describe the bug**
Setting maximum-scale in viewport meta has long been considered bad. It prevents users from being able to pinch-zoom should they need to.

**To Reproduce**
See the outputted html
look at meta tag for viewport:
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

**Expected behavior**
Should be:
<meta name="viewport" content="width=device-width, initial-scale=1.0">

**Desktop (please complete the following information):**
All
All
All

**Additional context**
https://a11yproject.com/posts/never-use-maximum-scale/

**Comment by ericalli** [comment]
Hey @tomliv,

Agreed! Feel free to submit a PR for this and I'll get it merged in ASAP. Otherwise, I'll get to it as soon as I have a moment.
