### ISSUE TITLE
Compression ratio of the images

### ISSUE THREAD

**Issue by cmateusmoraes** [ericalli/static-site-boilerplate#15]
**Question**
How to change the compression ratio of the images?

**Comment by ericalli** [comment]
The options for image compression are set in the [`config/webpack.loaders.js`](https://github.com/ericalli/static-site-boilerplate/blob/master/config/webpack.loaders.js#L97) file starting on line #97.

Image compression is done using the [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader) package. Check out their documentation for all the available options.
