### ISSUE TITLE
viewport, IE warning 

### ISSUE THREAD

**Issue by rafa-acioly** [ericalli/static-site-boilerplate#16]
What about adding `html` tags for `viewport` and the "IE hacking"?

inside head tag:
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

inside body tag:
```html
<!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
<![endif]-->
```

**Additional context**
there is some tags that maybe be helpfu: https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html

**Comment by ericalli** [comment]
Hey Rafa,

The boilerplate currently adds a `viewport` meta tag during the build process, it's configrable in the `config/site.config.js` file. The default value is:

```
<meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1">
```

As far as the IE warning, I'm hesitant to add any markup as a default in the HTML templates. It would be great to hear from other users if they are interested in this.
