### ISSUE TITLE
Easy way to add more JS or SCSS files

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [ericalli/static-site-boilerplate#18]
Is there a way to add more JS files?
Would I need to edit a config file to addmore JS files and set the order?

**Comment by ericalli** [comment]
No config file changes are necessary. Simply "import" your SCSS or JavaScript files from the main `styles.scss` or `scripts.js` files respectively.

For example, within the `styles.scss` file, you can add another stylesheet called `example.scss` by using the following line of code:

```
@import "example.scss"
```

References:

https://sass-lang.com/guide#topic-5
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
