### ISSUE TITLE
JS gets added to bottom of body can I have it in head?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [ericalli/static-site-boilerplate#19]
I installed Vue.js using NPM and load it in scripts.js:
`import 'vue';`

But it does not work since the scripts get loaded at the bottom of the body, any way to move it to head?

**Comment by lovenick** [comment]
That shouldn't matter - it's generally better to load your JS after the HTML has loaded unless you're using the "defer" attribute. 

You sure you're importing Vue correctly?

**Comment by DESIGNfromWITHIN** [comment]
Ok thx ill check

**Comment by ericalli** [comment]
@DESIGNfromWITHIN I'm assuming you got this working? If not, feel free to open a new issue.
