### ISSUE TITLE
dploy is no longer maintained

### ISSUE THREAD

**Issue by thegrandpoobah** [ericalli/static-site-boilerplate#25]
**Describe the bug**
The dploy package (https://github.com/lucasmotta/dploy) is currently unmaintained. While it still works, it might be wise to look for an alternative?

**Expected behavior**
This package should use maintained dependencies wherever possible.

**Comment by ericalli** [comment]
Good call. I'm looking into this for the next release.

Any suggestions on a replacement?

**Comment by thegrandpoobah** [comment]
I'm sorry, I don't have thoughts around what is available in terms of libraries. On my project, which uses a Linux development environment, I just ended up using rsync instead, but I don't think that works for a project such as this.

**Comment by ericalli** [comment]
Looks like [ftp-deploy](https://github.com/simonh1000/ftp-deploy) is a viable replacement. Unless anyone has any objections, I'll work on getting this swapped out!

**Comment by ericalli** [comment]
The deploy package has been replaced with ftp-deploy 2cda46f03b6a8a33de150bec00e17ad75cc67d84
