### ISSUE TITLE
invalid 'test' regex for javascript loader

### ISSUE THREAD

**Issue by armno** [ericalli/static-site-boilerplate#26]
**Describe the bug**
In [`config/webpack.loaders.js`, line 19](https://github.com/ericalli/static-site-boilerplate/blob/master/config/webpack.loaders.js#L19), the `test` regex matches only `.jsx` but not `.js` files.

`x` should be optional with `?` to match both `.js` and `.jsx` files.

```diff
- /\.js(x)$/
+ /\.js(x)?$/

// or something like
+ /\.jsx?$/
+ /\.(js|jsx)$/ 
```
(taken from https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L29)

tested with https://www.regextester.com/

<img width="183" alt="js" src="https://user-images.githubusercontent.com/911894/54329339-d877e500-4643-11e9-9edb-2a95552de2ea.png">
<img width="202" alt="optional-x" src="https://user-images.githubusercontent.com/911894/54329365-fb09fe00-4643-11e9-87f5-de7b41291721.png">

**To Reproduce**
1. Create a new project from the [installation guide](https://github.com/ericalli/static-site-boilerplate#installation)
2. Run `$ npm install`
3. Start dev server with `$ npm start`
4. In [`config/webpack.loaders.js`, line 23](https://github.com/ericalli/static-site-boilerplate/blob/master/config/webpack.loaders.js#L23), change `loader` from `babel-loader` to an invalid loader name, for example: `dumbbell-loader`
5. Restart the dev server. There is no errors thrown.

**Expected behavior**
webpack-dev-server should display an error of the invalid loader, which means the source file `scripts.js` get processed.

**Screenshots (of the expected behavior)**
<img width="1440" alt="Screen Shot 2019-03-14 at 10 36 39" src="https://user-images.githubusercontent.com/911894/54329664-2f31ee80-4645-11e9-8347-3bb14447a3b3.png">

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Node: v11.11.0
- npm: v6.9.0

**Additional context**
`.js` files are included in the bundle but they are not transpiled with `babel-loader`

✌️

**Comment by ericalli** [comment]
Good catch, i'll get this updated ASAP. Thanks!
