### ISSUE TITLE
Not Able to Install on Windows: Error: pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by shallabh** [ericalli/static-site-boilerplate#33]
**Describe the bug**
Error: pngquant failed to build, make sure that libpng-dev is installed
Tried installing libpng doesn't work. Tried isntalling manually doesn't work. Please let me know how to solve this, to use the Static Bolier Plate

**To Reproduce**
1. npm install
2. Runs installation
3. Error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ericalli** [comment]
This may offer some insight/actions that you can try to get it working:

https://github.com/imagemin/imagemin-pngquant/issues/46#issuecomment-515808859

Let me know if that does the trick, otherwise I'll investigate further.

**Comment by shallabh** [comment]
It worked, @ericalli ! Thanks a ton!
