### ISSUE TITLE
Fonts are not emitted to dist folder by file-loader

### ISSUE THREAD

**Issue by marioecg** [ericalli/static-site-boilerplate#34]
Custom fonts do not appear as they are not piped into the build process by Webpack's `file-loader`. This is the path I am using in my stylesheets:

```
@font-face {
  font-family: 'Font Name';
  src: url('/fonts/font-name.woff2') format('woff2'), url('/src/fonts/font-name.woff') format('woff');
  font-weight: normal;
  font-style: normal;
}
```

Font files are not emitted neither on development server `npm run start` nor production build `npm run build:dist`.

I checked this [issue's solution](https://github.com/webpack-contrib/file-loader/issues/32#issuecomment-250622904) but the result is the same.  Has anyone experienced a similar problem?

**Comment by ericalli** [comment]
Have you by chance tried using a relative path to your `fonts/` folder?

```
@font-face {
  font-family: 'Font Name';
  src: url('fonts/font-name.woff2') format('woff2'), url('fonts/font-name.woff') format('woff');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by marioecg** [comment]
Hey @ericalli! Thanks for the answer,

When changing to a relative path Webpack can't resolve each font's path and fails to compile. For some reason fonts are now displaying in the development server but still don't get piped when running the production build.

Have you dealt with a similar issue?

**Comment by ArvindBalgo** [comment]
Hello Marioecg,

Were you able to solve this issue?

**Comment by cerberart** [comment]
> Hello Marioecg,
> 
> Were you able to solve this issue?

Fonts are located in `src/fonts`. 
I tried to lower directory related to stylesheet file `../fonts/ `. 
All worked like a charm
