### ISSUE TITLE
Changes to files do not reflect in the browser

### ISSUE THREAD

**Issue by vladzima** [ericalli/static-site-boilerplate#4]
**Describe the bug**
Dev server. Changes to files do not reflect in the browser neither with hot reload nor with manual. Only relaunching server works.

**To Reproduce**
1. Install new boilerplate.
2. Make changed to index.html.
3. See no changes to the index page in the browser.

**Expected behavior**
Reflecting changes to the file at least with manual page reload.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome Version 71.0.3578.98
 - npm 6.2.0

**Comment by kalpsjo** [comment]
I too have this issue. I have reinstalled Node using Brew and ran nmp install.

OS: El Capitan
Browser: Chrome 71.0.3578.98
Node: 11.6.0
Npm 6.4.1

**Comment by w-stegmann** [comment]
Same issue right here. Updates and a clean install didn't help.

OS: macOS Mojave 10.14.2
Browser: Chrome 71.0.3578.98
Node: 11.7.0
npm: 6.5.0

**Comment by vladzima** [comment]
Yes, same, updates certainly didn't help.

**Comment by w-stegmann** [comment]
The [update](https://github.com/ericalli/static-site-boilerplate/commit/6a300efaaad71759903d33a5fd40c7cef94d4cd8) of _webpack-dev-server 3.1.10_ to 3.1.14 fucked it up. A downgrade temporarily fixed the issue for me.

1. Open package.json
2. Find _"webpack-dev-server": "^3.1.14"_
3. Replace with _"webpack-dev-server": "^3.1.10"_

**Comment by ericalli** [comment]
@w-stegmann is right. The update to webpack-dev-server is causing the issue -- I committed a downgrade until a compatible version is released.

**Comment by davidholtz** [comment]
I am also having this issue, despite the webpack-dev-server downgrade to "^3.1.10", which I do see.
OS: macOS Mojave 10.14.3

Browser: Firefox 65, but also happening in Chrome 71.0.3578.98
Node: 10.5.0
npm: 6.1.0

**Comment by davidholtz** [comment]
Started over after Installing Node 11.7.0 / npm 6.5.0, but didn't make a difference.

**Comment by w-stegmann** [comment]
Have you executed _npm install_ in the folder after changing the package.json?

**Comment by davidholtz** [comment]
Yeah, my process has been to remove the folder completely, use nvm to install/use a different/newer version, then follow Eric's steps from the beginning: 1. clone, 2. npm install, 3. npm run start.

**Comment by davidholtz** [comment]
The latest version of Eric's package.json file is calling webpack-dev-server 3.1.10 by default.

**Comment by davidholtz** [comment]
Hi. Just wanted to see if anyone else has been experiencing this issue or has any other advice for me. I am excited to jump in and use this thing.

**Comment by susan8098** [comment]
I just did a fresh install of this and having the same problem. The "webpack-dev-server" is set to "^3.1.10"

**Comment by ericalli** [comment]
@susan8098 This should be fixed in the latest release [v1.1.0](https://github.com/ericalli/static-site-boilerplate/releases/tag/1.1.0)
