### ISSUE TITLE
Use a templating/include engine

### ISSUE THREAD

**Issue by AdityaAnand1** [ericalli/static-site-boilerplate#51]
Going by this project means you just keep making more html files. That works fine if you have maybe two or three, but if you have dozens, that means that if you want to change the `<head>`/`<footer>`/`<nav>` on your website then you have to change it in every single file **manually**, which is insane.

Any mature static site setup should have a templating/partials/include engine setup.

https://www.staticgen.com/

**Comment by ericalli** [comment]
Actually, `interpolate: true` is configured as an `html-loader` options, so it's easy to add simple partial rendering like so:

```
Create a partial like:

_header.html

Require them in your template like:

${require('./_header.html')}
```

No templating engine needed :)

The upcoming version of Static Site Boilerplate will have enhanced support for templating engines using the [preprocessor](https://github.com/webpack-contrib/html-loader#preprocessor) option.
