### ISSUE TITLE
Images referenced in HTML are incorrectly deleted during production build

### ISSUE THREAD

**Issue by zgjimgjonbalaj** [ericalli/static-site-boilerplate#60]
**Describe the bug**
Images that are placed in the images folder but only referenced in HTML and not CSS do not get included in the production build. So far only tested with a PNG but would bet it includes others as well.

**To Reproduce**
1. Place an image in the /src/images/ folder.
2. Reference this image in index.html using /images/<image name>.png
3. Run the command npm run build:dist
4. Check the dist/images folder for your image.

**Expected behavior**
Images that are placed in the assets folder should not be removed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 2004
 - Browser [Brave (latest)]
 - NPM: 6.14.6
 - Node: 10.22.1
 - BoilerPlate: Current version

**Comment by zgjimgjonbalaj** [comment]
Just realized the loader expects no leading slash in the src attribute ie 

**Bad:** "/images/img-name.jpg"
**Good** "images/img-name.jpg"

I think it makes sense to add a wildcard there, many of us are used to relative URLs

**Comment by zgjimgjonbalaj** [comment]
Likewise in SCSS

**Bad**: "/images/img-name.jpg"
**Good**: "../images/img-name.jpg"

**Comment by puncture-design** [comment]
Images loaded via style and data attributes does not load in prod build

`<div style="background-image: url(images/slide-3d.jpg)">`
`<section data-image-src="images/bg-welcome.jpg">`

**Comment by joannaong** [comment]
Images loaded via style and data attributes does not load in prod build

For example, images here is not rendered in prod build
<div style="background-image: url(images/slide-3d.jpg)">
<section data-image-src="images/bg-welcome.jpg">

**Comment by ericalli** [comment]
When using images in your HTML, use the `require` syntax. `html-loader` will take care of copying over whatever you require into the `dist/` folder.

```
// Require images like so
${require('./images/photo.jpg')}

// Here's an example in your HTML
<div style="background-image: url(${require('./images/photo.jpg')})">
```
