### ISSUE TITLE
Unmodified clone doesn't build

### ISSUE THREAD

**Issue by deniskabana** [ericalli/static-site-boilerplate#67]
**UPDATE TO COME, SKIP NPM PART FOR NOW**

**Describe the bug**
Script `build:dist` fails with error on clean clone (without any modifications) during css parsing. Error was not catched, can't be easily diagnosed by through terminal output.

**To Reproduce**
1. Go to https://staticsiteboilerplate.com and finish all setup steps
2. Open dir, run `yarn && yarn build:dist`
3. See error

**Expected behavior**
Should build without errors.

**Screenshots**
Yarn (`yarn && yarn build:dist`) on a clean clone
<img width="1051" alt="Screenshot 2021-01-12 at 12 33 51" src="https://user-images.githubusercontent.com/8308865/104309553-a307e100-54d2-11eb-8e26-8b716142de8f.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Node.js 7.4.0
 - NPM version 7.4.0
 - Yarn version 1.22.10
 
 **Additional info**
After trying with npm only (without the use of yarn), I was able to see that the path to `terser` plugin is missing. I also tried installing `terser` manually to no avail. Below is a screenshot that should give pointers:
<img width="1055" alt="Screenshot 2021-01-12 at 12 56 42" src="https://user-images.githubusercontent.com/8308865/104311620-bec0b680-54d5-11eb-8780-975d42288da0.png">

**Comment by ericalli** [comment]
Thanks for the detailed info! I'm almost certain this is due to the older Node version you are currently using. If possible, upgrade to a version above Node v10 which should solve the issues you mentioned.
