### ISSUE TITLE
devServer hot reload does not working.  

### ISSUE THREAD

**Issue by skhtml** [ericalli/static-site-boilerplate#68]
**Describe the bug**
When i change pug/html , images it is okay when browser fully autoreload ,  but  when i update sass, / css files  i need only reload styles , but dont reload browser at all. 

**To Reproduce**
1.  type some rule  to  styles.scss file  
2. You can see that browser if fully reloading, 

**Expected behavior**
Browser not reloading,  it is only reload styles.  (thats much more quickly)

**Comment by ericalli** [comment]
Could you post a few details about your environment? 

- Node Version
- OS
- Any console errors

Thanks!
